name: flutter_defend
description: 'FlutterDefend 是一个轻量级的 Flutter 安全工具包，提供 SQL 注入检测、本地加密存储、安全输入框封装、越狱/root 检测等功能。'
version: 0.0.1
homepage: https://github.com/ctkqiang/flutter_defend
repository: https://github.com/ctkqiang/flutter_defend
issue_tracker: https://github.com/ctkqiang/flutter_defend/issues

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: '>=1.17.0'

topics:
  - security
  - encryption
  - sql-injection
  - jailbreak
  - secure-storage

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  no_screenshot: ^0.3.1
  flutter_root_jailbreak: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
